// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/sudobytemebaby/efir/services/room/internal/repository"

	uuid "github.com/google/uuid"
)

// RoomRepository is an autogenerated mock type for the RoomRepository type
type RoomRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, roomID, userID, role
func (_m *RoomRepository) AddMember(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, role repository.MemberRole) (*repository.RoomMember, error) {
	ret := _m.Called(ctx, roomID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 *repository.RoomMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, repository.MemberRole) (*repository.RoomMember, error)); ok {
		return rf(ctx, roomID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, repository.MemberRole) *repository.RoomMember); ok {
		r0 = rf(ctx, roomID, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.RoomMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, repository.MemberRole) error); ok {
		r1 = rf(ctx, roomID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoom provides a mock function with given fields: ctx, name, roomType, createdBy
func (_m *RoomRepository) CreateRoom(ctx context.Context, name string, roomType repository.RoomType, createdBy uuid.UUID) (*repository.Room, error) {
	ret := _m.Called(ctx, name, roomType, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.RoomType, uuid.UUID) (*repository.Room, error)); ok {
		return rf(ctx, name, roomType, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.RoomType, uuid.UUID) *repository.Room); ok {
		r0 = rf(ctx, name, roomType, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repository.RoomType, uuid.UUID) error); ok {
		r1 = rf(ctx, name, roomType, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRoom provides a mock function with given fields: ctx, id
func (_m *RoomRepository) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDirectRoomByUsers provides a mock function with given fields: ctx, userID1, userID2
func (_m *RoomRepository) GetDirectRoomByUsers(ctx context.Context, userID1 uuid.UUID, userID2 uuid.UUID) (*repository.Room, error) {
	ret := _m.Called(ctx, userID1, userID2)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectRoomByUsers")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*repository.Room, error)); ok {
		return rf(ctx, userID1, userID2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *repository.Room); ok {
		r0 = rf(ctx, userID1, userID2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID1, userID2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomByID provides a mock function with given fields: ctx, id
func (_m *RoomRepository) GetRoomByID(ctx context.Context, id uuid.UUID) (*repository.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByID")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repository.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repository.Room); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomMembers provides a mock function with given fields: ctx, roomID
func (_m *RoomRepository) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]repository.RoomMember, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomMembers")
	}

	var r0 []repository.RoomMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.RoomMember, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.RoomMember); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RoomMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsMember provides a mock function with given fields: ctx, roomID, userID
func (_m *RoomRepository) IsMember(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, roomID, userID
func (_m *RoomRepository) RemoveMember(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoom provides a mock function with given fields: ctx, id, name
func (_m *RoomRepository) UpdateRoom(ctx context.Context, id uuid.UUID, name string) (*repository.Room, error) {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*repository.Room, error)); ok {
		return rf(ctx, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *repository.Room); ok {
		r0 = rf(ctx, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoomRepository creates a new instance of RoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomRepository {
	mock := &RoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
