// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/sudobytemebaby/efir/services/message/internal/service"

	uuid "github.com/google/uuid"
)

// MessageService is an autogenerated mock type for the MessageService type
type MessageService struct {
	mock.Mock
}

// DeleteMessage provides a mock function with given fields: ctx, messageID, requesterID
func (_m *MessageService) DeleteMessage(ctx context.Context, messageID uuid.UUID, requesterID uuid.UUID) error {
	ret := _m.Called(ctx, messageID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, messageID, requesterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMessageByID provides a mock function with given fields: ctx, messageID, requesterID
func (_m *MessageService) GetMessageByID(ctx context.Context, messageID uuid.UUID, requesterID uuid.UUID) (*service.Message, error) {
	ret := _m.Called(ctx, messageID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByID")
	}

	var r0 *service.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*service.Message, error)); ok {
		return rf(ctx, messageID, requesterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *service.Message); ok {
		r0 = rf(ctx, messageID, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, messageID, requesterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessages provides a mock function with given fields: ctx, roomID, requesterID, cursor, limit
func (_m *MessageService) GetMessages(ctx context.Context, roomID uuid.UUID, requesterID uuid.UUID, cursor *uuid.UUID, limit int) ([]*service.Message, *uuid.UUID, error) {
	ret := _m.Called(ctx, roomID, requesterID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*service.Message
	var r1 *uuid.UUID
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, int) ([]*service.Message, *uuid.UUID, error)); ok {
		return rf(ctx, roomID, requesterID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, int) []*service.Message); ok {
		r0 = rf(ctx, roomID, requesterID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*service.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, int) *uuid.UUID); ok {
		r1 = rf(ctx, roomID, requesterID, cursor, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, int) error); ok {
		r2 = rf(ctx, roomID, requesterID, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendMessage provides a mock function with given fields: ctx, input
func (_m *MessageService) SendMessage(ctx context.Context, input *service.SendMessageInput) (*service.Message, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *service.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.SendMessageInput) (*service.Message, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.SendMessageInput) *service.Message); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.SendMessageInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
