// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/sudobytemebaby/efir/services/message/internal/service"

	uuid "github.com/google/uuid"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// PublishMessageCreated provides a mock function with given fields: ctx, msg, recipientIDs
func (_m *Publisher) PublishMessageCreated(ctx context.Context, msg *service.Message, recipientIDs []uuid.UUID) error {
	ret := _m.Called(ctx, msg, recipientIDs)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessageCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.Message, []uuid.UUID) error); ok {
		r0 = rf(ctx, msg, recipientIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
