http:
  routers:
    gateway:
      rule: "Host(`api.localhost`)"
      entrypoints:
        - web
      middlewares:
        - cors
        - rate-limit
      service: gateway

    websocket:
      rule: "Host(`ws.localhost`)"
      entrypoints:
        - web
      middlewares:
        - ws-forward-auth
      service: websocket

  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://efir-gateway:8080"

    websocket:
      loadBalancer:
        servers:
          - url: "http://efir-websocket:8081"
