linters:
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
    staticcheck:
      checks: ["all"]

  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - deadcode

run:
  timeout: 5m
  tests: true
