version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1020"
        - "-ST1003"

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
  tests: true
