// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// PublishMembershipChanged provides a mock function with given fields: ctx, roomID, userID, action, recipientIDs
func (_m *Publisher) PublishMembershipChanged(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, action string, recipientIDs []uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID, action, recipientIDs)

	if len(ret) == 0 {
		panic("no return value specified for PublishMembershipChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, []uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID, action, recipientIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishRoomUpdated provides a mock function with given fields: ctx, roomID, name, recipientIDs
func (_m *Publisher) PublishRoomUpdated(ctx context.Context, roomID uuid.UUID, name string, recipientIDs []uuid.UUID) error {
	ret := _m.Called(ctx, roomID, name, recipientIDs)

	if len(ret) == 0 {
		panic("no return value specified for PublishRoomUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, name, recipientIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
