// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/sudobytemebaby/efir/services/room/internal/repository"

	uuid "github.com/google/uuid"
)

// RoomService is an autogenerated mock type for the RoomService type
type RoomService struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, roomID, userID, requesterID
func (_m *RoomService) AddMember(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, requesterID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID, requesterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRoom provides a mock function with given fields: ctx, name, roomType, createdBy, participantID
func (_m *RoomService) CreateRoom(ctx context.Context, name string, roomType repository.RoomType, createdBy uuid.UUID, participantID uuid.UUID) (*repository.Room, error) {
	ret := _m.Called(ctx, name, roomType, createdBy, participantID)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.RoomType, uuid.UUID, uuid.UUID) (*repository.Room, error)); ok {
		return rf(ctx, name, roomType, createdBy, participantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.RoomType, uuid.UUID, uuid.UUID) *repository.Room); ok {
		r0 = rf(ctx, name, roomType, createdBy, participantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repository.RoomType, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, name, roomType, createdBy, participantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRoom provides a mock function with given fields: ctx, roomID, requesterID
func (_m *RoomService) DeleteRoom(ctx context.Context, roomID uuid.UUID, requesterID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, requesterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRoom provides a mock function with given fields: ctx, roomID
func (_m *RoomService) GetRoom(ctx context.Context, roomID uuid.UUID) (*repository.Room, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repository.Room, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repository.Room); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomMembers provides a mock function with given fields: ctx, roomID
func (_m *RoomService) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]repository.RoomMember, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomMembers")
	}

	var r0 []repository.RoomMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.RoomMember, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.RoomMember); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RoomMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsMember provides a mock function with given fields: ctx, roomID, userID
func (_m *RoomService) IsMember(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, roomID, userID, requesterID
func (_m *RoomService) RemoveMember(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, requesterID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID, requesterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoom provides a mock function with given fields: ctx, roomID, requesterID, name
func (_m *RoomService) UpdateRoom(ctx context.Context, roomID uuid.UUID, requesterID uuid.UUID, name string) (*repository.Room, error) {
	ret := _m.Called(ctx, roomID, requesterID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 *repository.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*repository.Room, error)); ok {
		return rf(ctx, roomID, requesterID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *repository.Room); ok {
		r0 = rf(ctx, roomID, requesterID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, roomID, requesterID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoomService creates a new instance of RoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomService {
	mock := &RoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
