# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]

tasks:
  lint:
    desc: Lint proto files
    cmds:
      - buf lint

  generate:
    desc: Generate Go code from proto files
    cmds:
      - buf generate
