// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/sudobytemebaby/efir/services/user/internal/service"

	uuid "github.com/google/uuid"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, userID, email
func (_m *UserService) CreateUser(ctx context.Context, userID uuid.UUID, email string) (*service.User, error) {
	ret := _m.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*service.User, error)); ok {
		return rf(ctx, userID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *service.User); ok {
		r0 = rf(ctx, userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *UserService) GetUser(ctx context.Context, userID uuid.UUID) (*service.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*service.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, userIDs
func (_m *UserService) GetUsers(ctx context.Context, userIDs []uuid.UUID) ([]service.User, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]service.User, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []service.User); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, userID, displayName, avatarURL, bio
func (_m *UserService) UpdateUser(ctx context.Context, userID uuid.UUID, displayName *string, avatarURL *string, bio *string) (*service.User, error) {
	ret := _m.Called(ctx, userID, displayName, avatarURL, bio)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, *string) (*service.User, error)); ok {
		return rf(ctx, userID, displayName, avatarURL, bio)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, *string) *service.User); ok {
		r0 = rf(ctx, userID, displayName, avatarURL, bio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *string, *string) error); ok {
		r1 = rf(ctx, userID, displayName, avatarURL, bio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
