// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/sudobytemebaby/efir/services/user/internal/repository"

	uuid "github.com/google/uuid"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, id, username, displayName
func (_m *UserRepository) CreateUser(ctx context.Context, id uuid.UUID, username string, displayName string) (*repository.User, error) {
	ret := _m.Called(ctx, id, username, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*repository.User, error)); ok {
		return rf(ctx, id, username, displayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *repository.User); ok {
		r0 = rf(ctx, id, username, displayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, username, displayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*repository.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repository.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repository.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByIDs provides a mock function with given fields: ctx, ids
func (_m *UserRepository) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]repository.User, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIDs")
	}

	var r0 []repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]repository.User, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []repository.User); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, id, displayName, avatarURL, bio
func (_m *UserRepository) UpdateUser(ctx context.Context, id uuid.UUID, displayName *string, avatarURL *string, bio *string) (*repository.User, error) {
	ret := _m.Called(ctx, id, displayName, avatarURL, bio)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, *string) (*repository.User, error)); ok {
		return rf(ctx, id, displayName, avatarURL, bio)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, *string) *repository.User); ok {
		r0 = rf(ctx, id, displayName, avatarURL, bio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *string, *string) error); ok {
		r1 = rf(ctx, id, displayName, avatarURL, bio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
