// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	roomv1 "github.com/sudobytemebaby/efir/services/shared/gen/room"
)

// RoomServiceClient is an autogenerated mock type for the RoomServiceClient type
type RoomServiceClient struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) AddMember(ctx context.Context, in *roomv1.AddMemberRequest, opts ...grpc.CallOption) (*roomv1.AddMemberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 *roomv1.AddMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.AddMemberRequest, ...grpc.CallOption) (*roomv1.AddMemberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.AddMemberRequest, ...grpc.CallOption) *roomv1.AddMemberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.AddMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.AddMemberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoom provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) CreateRoom(ctx context.Context, in *roomv1.CreateRoomRequest, opts ...grpc.CallOption) (*roomv1.CreateRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *roomv1.CreateRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.CreateRoomRequest, ...grpc.CallOption) (*roomv1.CreateRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.CreateRoomRequest, ...grpc.CallOption) *roomv1.CreateRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.CreateRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.CreateRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRoom provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) DeleteRoom(ctx context.Context, in *roomv1.DeleteRoomRequest, opts ...grpc.CallOption) (*roomv1.DeleteRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 *roomv1.DeleteRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.DeleteRoomRequest, ...grpc.CallOption) (*roomv1.DeleteRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.DeleteRoomRequest, ...grpc.CallOption) *roomv1.DeleteRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.DeleteRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.DeleteRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoom provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) GetRoom(ctx context.Context, in *roomv1.GetRoomRequest, opts ...grpc.CallOption) (*roomv1.GetRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *roomv1.GetRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.GetRoomRequest, ...grpc.CallOption) (*roomv1.GetRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.GetRoomRequest, ...grpc.CallOption) *roomv1.GetRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.GetRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.GetRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomMembers provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) GetRoomMembers(ctx context.Context, in *roomv1.GetRoomMembersRequest, opts ...grpc.CallOption) (*roomv1.GetRoomMembersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomMembers")
	}

	var r0 *roomv1.GetRoomMembersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.GetRoomMembersRequest, ...grpc.CallOption) (*roomv1.GetRoomMembersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.GetRoomMembersRequest, ...grpc.CallOption) *roomv1.GetRoomMembersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.GetRoomMembersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.GetRoomMembersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsMember provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) IsMember(ctx context.Context, in *roomv1.IsMemberRequest, opts ...grpc.CallOption) (*roomv1.IsMemberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 *roomv1.IsMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.IsMemberRequest, ...grpc.CallOption) (*roomv1.IsMemberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.IsMemberRequest, ...grpc.CallOption) *roomv1.IsMemberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.IsMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.IsMemberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) RemoveMember(ctx context.Context, in *roomv1.RemoveMemberRequest, opts ...grpc.CallOption) (*roomv1.RemoveMemberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 *roomv1.RemoveMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.RemoveMemberRequest, ...grpc.CallOption) (*roomv1.RemoveMemberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.RemoveMemberRequest, ...grpc.CallOption) *roomv1.RemoveMemberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.RemoveMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.RemoveMemberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRoom provides a mock function with given fields: ctx, in, opts
func (_m *RoomServiceClient) UpdateRoom(ctx context.Context, in *roomv1.UpdateRoomRequest, opts ...grpc.CallOption) (*roomv1.UpdateRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 *roomv1.UpdateRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.UpdateRoomRequest, ...grpc.CallOption) (*roomv1.UpdateRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roomv1.UpdateRoomRequest, ...grpc.CallOption) *roomv1.UpdateRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roomv1.UpdateRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roomv1.UpdateRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoomServiceClient creates a new instance of RoomServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomServiceClient {
	mock := &RoomServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
