// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/sudobytemebaby/efir/services/auth/internal/repository"

	uuid "github.com/google/uuid"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: ctx, email, passwordHash
func (_m *AccountRepository) CreateAccount(ctx context.Context, email string, passwordHash string) (*repository.Account, error) {
	ret := _m.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *repository.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*repository.Account, error)); ok {
		return rf(ctx, email, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *repository.Account); ok {
		r0 = rf(ctx, email, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByEmail provides a mock function with given fields: ctx, email
func (_m *AccountRepository) GetAccountByEmail(ctx context.Context, email string) (*repository.Account, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByEmail")
	}

	var r0 *repository.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repository.Account, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repository.Account); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByID provides a mock function with given fields: ctx, id
func (_m *AccountRepository) GetAccountByID(ctx context.Context, id uuid.UUID) (*repository.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 *repository.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repository.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repository.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
