// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/sudobytemebaby/efir/services/message/internal/repository"

	uuid "github.com/google/uuid"
)

// MessageRepository is an autogenerated mock type for the MessageRepository type
type MessageRepository struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: ctx, input
func (_m *MessageRepository) CreateMessage(ctx context.Context, input *repository.CreateMessageInput) (*repository.Message, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *repository.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.CreateMessageInput) (*repository.Message, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.CreateMessageInput) *repository.Message); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.CreateMessageInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessageByID provides a mock function with given fields: ctx, messageID
func (_m *MessageRepository) GetMessageByID(ctx context.Context, messageID uuid.UUID) (*repository.Message, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByID")
	}

	var r0 *repository.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repository.Message, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repository.Message); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessagesByRoomID provides a mock function with given fields: ctx, roomID, cursor, limit
func (_m *MessageRepository) GetMessagesByRoomID(ctx context.Context, roomID uuid.UUID, cursor *uuid.UUID, limit int) ([]*repository.Message, *uuid.UUID, error) {
	ret := _m.Called(ctx, roomID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesByRoomID")
	}

	var r0 []*repository.Message
	var r1 *uuid.UUID
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int) ([]*repository.Message, *uuid.UUID, error)); ok {
		return rf(ctx, roomID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int) []*repository.Message); ok {
		r0 = rf(ctx, roomID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, int) *uuid.UUID); ok {
		r1 = rf(ctx, roomID, cursor, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *uuid.UUID, int) error); ok {
		r2 = rf(ctx, roomID, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SoftDeleteMessage provides a mock function with given fields: ctx, messageID
func (_m *MessageRepository) SoftDeleteMessage(ctx context.Context, messageID uuid.UUID) error {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageRepository creates a new instance of MessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageRepository {
	mock := &MessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
