# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  auth:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    container_name: efir-auth
    env_file:
      - .env
    environment:
      - POSTGRES_DSN=${POSTGRES_AUTH_DSN}
      - GRPC_PORT=${AUTH_GRPC_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - efir-network

  user:
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    container_name: efir-user
    env_file:
      - .env
    environment:
      - GRPC_PORT=${USER_GRPC_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - efir-network

  room:
    build:
      context: .
      dockerfile: ./services/room/Dockerfile
    container_name: efir-room
    env_file:
      - .env
    environment:
      - GRPC_PORT=${ROOM_GRPC_PORT}
      - POSTGRES_DSN=${POSTGRES_ROOM_DSN}
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - efir-network

  message:
    build:
      context: .
      dockerfile: ./services/message/Dockerfile
    container_name: efir-message
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
      room:
        condition: service_started
    networks:
      - efir-network

  websocket:
    build:
      context: .
      dockerfile: ./services/websocket/Dockerfile
    container_name: efir-websocket
    env_file:
      - .env
    depends_on:
      nats:
        condition: service_healthy
    networks:
      - efir-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.websocket.rule=Host(`ws.localhost`)"
      - "traefik.http.routers.websocket.entrypoints=web"
      - "traefik.http.services.websocket.loadbalancer.server.port=8081"

  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    container_name: efir-gateway
    env_file:
      - .env
    depends_on:
      auth:
        condition: service_started
      user:
        condition: service_started
      room:
        condition: service_started
      message:
        condition: service_started
      valkey:
        condition: service_healthy
    networks:
      - efir-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.localhost`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"

networks:
  efir-network:
    external: true
