// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	messagev1 "github.com/sudobytemebaby/efir/services/shared/gen/message"

	mock "github.com/stretchr/testify/mock"
)

// MessageServiceClient is an autogenerated mock type for the MessageServiceClient type
type MessageServiceClient struct {
	mock.Mock
}

// DeleteMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessageServiceClient) DeleteMessage(ctx context.Context, in *messagev1.DeleteMessageRequest, opts ...grpc.CallOption) (*messagev1.DeleteMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 *messagev1.DeleteMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.DeleteMessageRequest, ...grpc.CallOption) (*messagev1.DeleteMessageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.DeleteMessageRequest, ...grpc.CallOption) *messagev1.DeleteMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messagev1.DeleteMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *messagev1.DeleteMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessageById provides a mock function with given fields: ctx, in, opts
func (_m *MessageServiceClient) GetMessageById(ctx context.Context, in *messagev1.GetMessageByIdRequest, opts ...grpc.CallOption) (*messagev1.GetMessageByIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageById")
	}

	var r0 *messagev1.GetMessageByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.GetMessageByIdRequest, ...grpc.CallOption) (*messagev1.GetMessageByIdResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.GetMessageByIdRequest, ...grpc.CallOption) *messagev1.GetMessageByIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messagev1.GetMessageByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *messagev1.GetMessageByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessages provides a mock function with given fields: ctx, in, opts
func (_m *MessageServiceClient) GetMessages(ctx context.Context, in *messagev1.GetMessagesRequest, opts ...grpc.CallOption) (*messagev1.GetMessagesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 *messagev1.GetMessagesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.GetMessagesRequest, ...grpc.CallOption) (*messagev1.GetMessagesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.GetMessagesRequest, ...grpc.CallOption) *messagev1.GetMessagesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messagev1.GetMessagesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *messagev1.GetMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessageServiceClient) SendMessage(ctx context.Context, in *messagev1.SendMessageRequest, opts ...grpc.CallOption) (*messagev1.SendMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *messagev1.SendMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.SendMessageRequest, ...grpc.CallOption) (*messagev1.SendMessageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *messagev1.SendMessageRequest, ...grpc.CallOption) *messagev1.SendMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messagev1.SendMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *messagev1.SendMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMessageServiceClient creates a new instance of MessageServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageServiceClient {
	mock := &MessageServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
