name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml

  proto:
    needs: validate
    uses: ./.github/workflows/_proto.yml

  go:
    needs: proto
    uses: ./.github/workflows/_go.yml
    with:
      has-proto: ${{ needs.proto.outputs.has-proto }}

  build:
    needs: go
    uses: ./.github/workflows/_build.yml
